---
abstract: 'JQuery for Perl programmers'
author:
  - 'Brad Haywood <bradh@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-JQuery
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: git://somewhere.com/myproject.git
version: 1.1.1
